### ISSUE TITLE
Upload Speed Test

### ISSUE THREAD

**Issue by jsavko** [karelkryda/universal-speedtest#12]
The upload speedtest payload is too small to get an accurate upload speed in most instances.  Adjusting the cloudflare payload to ```            upload: [
                [1001000, 8],
                [10001000, 6]
            ]```
produced much better results.   Allowing the upload payload to be set as an option would be wonderful

**Comment by karelkryda** [comment]
Thank you, I'll look into it

**Comment by karelkryda** [comment]
I apologize for the later response. I'm a little under time pressure.

I've released version 2.0.3, which updates all dependencies to the latest versions and adds the ability to specify downloadPayload and uploadPayload.

I left uploadPayload because the test did not complete within 2 minutes when tested on a slower internet connection, which could negatively affect users who use this test. But you can now adjust the size of the payload yourself.
I am now updating the documentation to reflect the current changes.

Thank you for your time.
