### ISSUE TITLE
[BUG] : Depreceated

### ISSUE THREAD

**Issue by Sahil-Gulihar** [karelkryda/universal-speedtest#28]
**Describe the bug**

**To Reproduce**
1. Setup locally
2. Install universal-speedtest
3. Run the main file with code
```js
const { UniversalSpeedtest, SpeedUnits } = require('universal-speedtest');

const universalSpeedtest = new UniversalSpeedtest({
    measureUpload: true,
    downloadUnit: SpeedUnits.MBps
});

universalSpeedtest.runSpeedtestNet().then(result => {
    console.log(`Ping: ${result.ping} ms`);
    console.log(`Download speed: ${result.downloadSpeed} MBps`);
    console.log(`Upload speed: ${result.uploadSpeed} Mbps`);
}).catch(e => {
    console.error(e.message);
});
```
<img width="1240" alt="image" src="https://github.com/user-attachments/assets/66767f85-2aa1-425b-95be-2a51a987b183">

**Comment by karelkryda** [comment]
Hello,
I started a complete rewrite of the library in February. One of the benefits should be much higher quality testing using Ookla Speedtest. Unfortunately the last few months have been very chaotic for me and I never finished this release. Today I found the time to get started again. At the current stage, I just need to rewrite the upload speed measurement technology and make a few minor improvements. The beta release of the new version `3.0.0` will probably be stripped of the ability to use the Cloudflare test for testing, but I believe most users primarily use the Ookla test anyway, which is why I've given it my full effort.

This release will use different libraries, different technologies and different ways of packaging the resulting code. This should solve the problem you mentioned.

I ask for your patience until the new release comes out. I will try to devote all my spare time to it if possible.

Translated with DeepL.com (free version)

**Comment by karelkryda** [comment]
Hello @Sahil-Gulihar,
I just [released](https://github.com/karelkryda/universal-speedtest/releases/tag/v3.0.0-rc.0) the release candidate of version `3.0.0`.
You can install and test the library using:
```bash
npm install --save universal-speedtest@next
```

The new documentation can be found here: https://karel-kryda.gitbook.io/universal-speedtest/v/3

I hope everything will work as expected 😉.
