### ISSUE TITLE
[BUG] TypeError: UniversalSpeedtest is not a constructor - when using V3.0.0 from the build branch

### ISSUE THREAD

**Issue by sjonniesensei** [karelkryda/universal-speedtest#29]
**Describe the bug**
Im getting the error TypeError: UniversalSpeedtest is not a constructor. 

**To Reproduce**
1. install universalspeedtest v 3.0.0 from the build branch
2. setup an express server. Here is the code of my express server.js file:
`const express = require("express");
const { UniversalSpeedtest, SpeedUnits } = require("universal-speedtest");

const app = express();
const port = 3000;

app.use(express.static("public"));

app.get("/api/speedtest", async (req, res) => {
  const universalSpeedtest = new UniversalSpeedtest({
    measureUpload: true,
    downloadUnit: SpeedUnits.MBps,
  });
  universalSpeedtest
    .runSpeedtestNet()
    .then((result) => {
      res.json({ speed: result });
    })
    .catch((error) => {
      res.status(500).json({ error: error.message });
    });
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
`
3. run "node server.js"
4. you will see the error in the terminal

**Expected behavior**
expected the results of the speed test as I made an index.html with a script where Im calling the /api/speedtest:
`function runSpeedtest() {
  startTestButton.disabled = true;

  const eventSource = new EventSource("/api/speedtest");

  eventSource.onmessage = function (event) {
    const data = JSON.parse(event.data);
    console.log(data);

    if (data.type === "complete") {
      eventSource.close();
      startTestButton.disabled = false;
    }
  };

  eventSource.onerror = function (error) {
    console.error("EventSource failed:", error);
    eventSource.close();
    startTestButton.disabled = false;
  };
}`

**Screenshots**
![Screenshot 2024-09-15 150135](https://github.com/user-attachments/assets/b8994a4e-9898-46ad-9530-af610cd8823b)

**Desktop (please complete the following information):**
 - OS: windows
 - Node.js version: v20.15.1
 - Universal Speedtest version: 3.0.0
 - Speed test using:  speedtest.net

**Comment by karelkryda** [comment]
Hello,

I remember that in the original version `3.0.0` I made modifications including renaming methods and constructors. However, by never officially releasing this version, I believe I have not updated the documentation either.

In February, I started a complete rewrite of the library. One of the benefits should be much higher quality testing using Ookla Speedtest. Unfortunately the last few months have been very chaotic for me and I never finished this release. Today I found the time to get started again. At the current stage, I just need to rewrite the upload speed measurement technology and make a few minor improvements. The beta release of the new version `3.0.0` will probably be stripped of the ability to use the Cloudflare test for testing, but I believe most users primarily use the Ookla test anyway, which is why I've given it my full effort.

This release will use different libraries, different technologies and different ways of packaging the resulting code. This should solve the problem you mentioned.

I ask for your patience until the new release comes out. I will try to devote all my spare time to it if possible.

**Comment by sjonniesensei** [comment]
Hi @karelkryda ,

Thanks for the reaction.
Alright, looking forward to the new version. Please let me know when it is out.

Have a good day!

**Comment by WebDevDatasur** [comment]
Hi @karelkryda ,

Any update on this?

**Comment by sjonniesensei** [comment]
Hi @karelkryda ,

Any update on this?

**Comment by karelkryda** [comment]
Hi @sjonniesensei,
yes, yesterday I made the last changes regarding functionality and code cleaning.

I plan to release an RC version soon, but before that, I'd like to do some testing for accuracy - to make sure everything works as expected on a connection other than mine.
I also have to prepare new documentation and then test the code externally in an example project.

I plan to implement some more functionalities, but I can do it even after the release of the first RC version - I would like to see this functionality in the stable version 3.0.0.

However, I have to say that I am extremely satisfied and I am really looking forward to the release. Compared to previous versions, the library is much faster, more accurate and offers much more output data.

I plan to release at least the first RC version this weekend - if everything goes according to plan.

Thanks for your patience

**Comment by sjonniesensei** [comment]
This bug has been fixed with the new version. Thanks @karelkryda .

**Comment by surya123866** [comment]
> This bug has been fixed with the new version. Thanks [@karelkryda](https://github.com/karelkryda) .

I am still facing a similar issue. How can I resolve it?

**Comment by karelkryda** [comment]
Hi @surya123866,
use the latest version of the library and follow the documentation for version 3.

In case of problems, do not hesitate to open a new issue and provide the necessary information about your problem, including your code.

Have a nice day
